# Generated by Django 2.0.2 on 2018-10-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181002_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hunter',
            new_name='hunter_id',
        ),
    ]
