# Generated by Django 2.0.2 on 2018-10-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181002_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hunter_id',
            new_name='hunter',
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
